<?php

if (!defined("BLOCK")) {
    exit("\r\n\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /> \r\n\t\t<html>\r\n\t\t\t<head>\r\n\t\t\t\t<title>404 Not Found</title>\r\n\t\t\t</head>\r\n\t\t\t<body>\r\n\t\t\t\t<h1>Not Found</h1>\r\n\t\t\t\t<p>The requested URL was not found on this server.</p>\r\n\t\t\t</body>\r\n\t\t</html>");
}
require_once "core/core.php";
$type = "donate";
if (isset($_POST["donate"])) {
    $desc = "Донат от " . $_POST["nick"];
    $sign = md5("" . $free_login . ":" . $_POST["summ"] . ":" . $_POST["nick"] . ":" . $free_pass1 . ":Shp_id=" . $_POST["nick"] . ":Shp_t=:Shp_type=" . $type . "");
    $db->m_query("INSERT INTO `" . DBcfg::$dbopt["db_prefix"] . "_donate_history` ( `nick`, `summ`, `sign` ) VALUES ('" . $db->m_escape(trim($_POST["nick"])) . "', '" . $db->m_escape(trim($_POST["summ"])) . "', '" . $sign . "')");
    echo "\r\n            <html> \r\n            <head>\r\n                <title>Переадресация на сайт платёжной системы...</title>\r\n                <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n                <meta http-equiv=\"Content-Language\" content=\"ru\">\r\n                <meta http-equiv=\"Pragma\" content=\"no-cache\">\r\n                <meta name=\"robots\" content=\"noindex,nofollow\">\r\n            </head>\r\n            <body>";
    echo "\r\n\t\t\t<form name=\"oplata\" method=\"GET\" action=\"https://www.free-kassa.ru/merchant/cash.php\">\r\n\t\t\t<input type=\"hidden\" name=\"MrchLogin\" value=\"" . $free_login . "\" />\r\n\t\t\t<input type=\"hidden\" name=\"OutSum\" value=\"" . $_POST["summ"] . "\" />\r\n\t\t\t<input type=\"hidden\" name=\"InvId\" value=\"" . $_POST["nick"] . "\" />\r\n\t\t\t<input type=\"hidden\" name=\"Desc\" value=\"" . $desc . "\" />\r\n\t\t\t<input type=\"hidden\" name=\"SignatureValue\" value=\"" . $sign . "\" />\r\n\t\t\t<input type=\"hidden\" name=\"Culture\" value=\"ru\" />\r\n\t\t\t<input type=\"hidden\" name=\"Encoding\" value=\"utf-8\" />\r\n\t\t\t<input type=\"hidden\" name=\"Shp_id\" value=\"" . $_POST["nick"] . "\" />\r\n            <input type=\"hidden\" name=\"Shp_t\" value=\"\" />\r\n            <input type=\"hidden\" name=\"Shp_type\" value=\"" . $type . "\" />";
    echo "\r\n\t\t\t<noscript><input type=\"submit\" value=\"Нажмите, если не хотите ждать!\" onclick=\"document.oplata.submit();\"></noscript>\r\n\t\t</form>\r\n\t\t<script language=\"Javascript\" type=\"text/javascript\">\r\n\t\t\tdocument.oplata.submit();\r\n\t\t</script>\r\n\t</body>\r\n\t</html>";
}
echo "\r\n    <div class=\"tab-pane fade\" id=\"donate\" role=\"tabpanel\" aria-labelledby=\"donate-tab\">\r\n    <div class=\"callout callout-warning\">\r\n        <b>Информация:</b><br>\r\n        Данная страничка предназначена для пожертвований проекту.\r\n        Благодарим Вас за оказание помощи нашему проекту.\r\n        После оплаты Вы будете добалвены в список ТОП-Донатеров.\r\n        Вопросы:<br><br>\r\n        <b>Для чего нужен Ник?</b><br>Ник нужен для отображения Вас в списке ТОП-Донатеров.<br><br>\r\n        <b>Сколько я могу задонатить?</b><br>Задонатить Вы можете любую сумму.\r\n    </div>\r\n    <form role=\"form\" action=\"\" method=\"POST\" autocomplete=\"off\">\r\n        <label>Введите ник:</label>\r\n        <div class=\"input-group\">\r\n            <div class=\"input-group-prepend\">\r\n                <span class=\"input-group-text\"><i class=\"far fa-user\"></i></span>\r\n            </div>\r\n            <input id=\"nick\" name=\"nick\" placeholder=\"\" class=\"form-control\" required=\"\" type=\"text\">\r\n        </div>\r\n        <div class=\"form-group\">\r\n            <label>Введите сумму:</label>\r\n            <div class=\"input-group\">\r\n                <div class=\"input-group-prepend\">\r\n                    <span class=\"input-group-text\"><i class=\"fa fa-money\"></i></span>\r\n                </div>\r\n                <input id=\"summ\" name=\"summ\" value=\"10\" class=\"form-control\" min=\"10\" required=\"\" type=\"number\">\r\n            </div>\r\n            <input class=\"btn btn-block btn-outline-success\" type=\"submit\" value=\"Пожертвовать\" id=\"donate\" name=\"donate\">\r\n            <div class=\"card-footer\">\r\n                <div class=\"custom-control custom-checkbox\">\r\n                    <input class=\"custom-control-input\" type=\"checkbox\" checked>\r\n                    <label for=\"customCheckbox2\" class=\"custom-control-label\"></label> Нажимая кнопку\r\n                    \"пожертвовать\" вы соглашаетесь с условиями проекта.\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div></div></div>";

?>